sudo: false
dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=5.8.*

before_script:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require "illuminate/redis:${LARAVEL_VERSION}" --no-update; fi;
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
