name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  schedule:
  - cron: "0 0 * * 5"

jobs:
  PHPUnit:

    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.0']
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: PHPUnit Tests - ${{ matrix.php_versions }} - ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}
        extensions: mbstring, dom, fileinfo, gd
        coverage: xdebug
        tools: pecl

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Setup Redis-server
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - name: Setup Memcached
      uses: niden/actions-memcached@v7

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit

    - name: Upload coverage to Codecov
      if: github.event_name != 'schedule'
      uses: codecov/codecov-action@v1
      with:
        file: ./_meta/coverage.xml
        fail_ci_if_error: true
