name: CI

on:
  push:
    branches: [develop-5.0]
  pull_request:
    branches: [develop-5.0]
  workflow_dispatch:

jobs:
  PHPStan:

    runs-on: ubuntu-latest
    name: PHPStan

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        php_version: 8.0
        path: src/UniformResourceLocator/ src/Config
